config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :day_texts, only: [:create]
  resources :reports, only: [:create, :index] do
    collection do
      get 'raw'
      get 'demo'
    end
  end

  root to: 'reports#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates_confirmation_of :password

  # Include default devise modules. Others available are:
  # :registerable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable,
         :lockable, :invitable
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_authorization_check
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_from_url_param, only: [:edit, :update, :show, :destroy]
  before_action :invite_user, only: :create
  load_and_authorize_resource

  def index
    if current_user.admin?
      @users = User.all.order(created_at: :desc)
    else
      @users = User.where(id: current_user.id)
    end
  end

  def new
    @user = User.new
  end

  def create
    if @user.save
      flash[:notice] = 'The User is successfully saved!'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'The User is successfully updated!'
      if current_user.admin?
        redirect_to users_path
      else
        redirect_to edit_user_path(current_user)
      end
    else
      flash[:error] = @user.errors.full_messages[0]
      render 'edit'
    end
  end

  def destroy
    unless @user.admin?
      @user.destroy

      flash[:notice] = 'The User was successfully deleted'
      redirect_to users_path
    else

      flash[:error] = 'You can not destroy this user'
      redirect_to users_path
    end
  end

  private

  def invite_user
    @user = User.invite!(user_params)
  end

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if current_user.admin?
      params.require(:user).permit(:email, :first_name, :last_name, :admin, :password, :password_confirmation)
    else
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end
  end

  def user_from_url_param
    @user = User.find(params[:id])
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-4 control-label' %>
    <div class="col-sm-8">
      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :first_name, class: 'col-sm-4 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: 'col-sm-4 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
    </div>
  </div>

  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :admin, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.check_box :admin %>
      </div>
    </div>
  <% end %>

  <% if with_password %>
    <div class="form-group">
      <%= f.label :password, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password'%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: 'col-sm-4 control-label' %>
      <div class="col-sm-8">
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Password Confirmation'%>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
      <%= f.submit class: 'btn btn-success' %>
      <%= link_to 'Back', :back, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', with_password: true %>

app/views/users/index.html.erb
<h1 class="title">Users</h1>
<% if current_user.admin? %>
  <%= link_to new_user_path, class: 'btn btn-success add-button' do %>
    <i class="fa fa-plus" aria-hidden="true"></i>
    Invite user
  <% end %>
<% end %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Type</th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr class="<%= user == current_user ? 'info' : '' %>">
          <td><%= user.email %></td>
          <td><%= user.admin ? 'Admin' : 'User' %></td>
          <td class="actions">
            <% if current_user.admin? && !user.admin? %>
              <%= link_to user_path(user), class: 'btn btn-sm btn-danger', method: :delete, data: {:confirm => 'Would you really destroy that user?'} do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
                Delete
              <% end %>
            <% end %>
            <%= link_to edit_user_path(user), class: 'btn btn-sm btn-primary' do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
              Edit
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', with_password: false %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>