config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :day_texts, only: [:create]
  resources :reports, only: [:create, :index] do
    collection do
      get 'raw'
      get 'demo'
    end
  end

  root to: 'reports#index'
end

app/models/report.rb
require 'csv'

class Report < ApplicationRecord
  # associations
  has_many :trees, inverse_of: :report, dependent: :destroy
  belongs_to :device, inverse_of: :reports

  # validations
  validates :site_reference, :site_id, :visit_id, :taken_at, presence: true

  # accept nested parameters
  accepts_nested_attributes_for :trees

  #scopes
  scope :demo, -> { where(demo: true) }
  scope :real, -> { where("demo IS NULL or demo = false") }

  #-----------------------#
  #     class methods     #
  #-----------------------#

  def self.transpose_params(params)
    return {} unless params.is_a?(Hash)

    device = Device.find_or_create_by(uuid: params['d1'])

    report_params = { report: {
      taken_at: (params['p1'] ? Date.parse(params['p1']).to_datetime : nil),
      site_reference: params['p2'],
      site_id: params['p3'],
      visit_id: params['p4'],
      humidity: params['p5'],
      canopy: params['p6'],
      leaf: params['p7'],
      maintenance: params['p8'],
      flowers: params['p9'],
      bp: !!(params['p10'].to_s =~ /yes/i),
      harvesting: !!(params['p11'].to_s =~ /yes/i),
      drying: !!(params['p12'].to_s =~ /yes/i),
      fertilizer: !!(params['p13'].to_s =~ /yes/i),
      wilt: !!(params['p14'].to_s =~ /yes/i),
      region: params['p15'],
      site_active_gps: params['s1'],
      site_latitude: params['s2'],
      site_longitude: params['s3'],
      site_accuracy: params['s4'],
      site_age: params['s5'],
      device_id: device.id,
      demo: (params['d2'].to_s == '1')
    }}

    if device.uuid == '71739E5944834FAC8EF9CA534CE20240'
      report_params[:report][:demo] = false
    end


    report_params[:report][:trees_attributes] = transpose_trees_params(params)

    report_params
  rescue
    {}
  end

  def self.transpose_trees_params(params)
    trees_index = 1
    trees_params = []

    while params["t#{trees_index}"].present?
      trees_params << Tree.transpose_params(params["t#{trees_index}"])
      trees_index += 1
    end

    trees_params
  end

  def self.to_csv(date = DateTime.yesterday, options = {})
    header_names = [
      'date', 'site_reference', 'country', 'site_longitude', 'site_latitude', 'site_age', 'device', 'humidity', 'canopy', 'leaf', 'maintenance', 'flowers', 'bp', 'wilt', 'harvesting', 'drying', 'fertilizer',
      'tree1_tiny', 'tree1_small', 'tree1_small2', 'tree1_large', 'tree1_mature', 'tree1_rife', 'tree1_infest', 'tree1_force_r', 'tree1_blackpod',
      'tree2_tiny', 'tree2_small', 'tree2_small2', 'tree2_large', 'tree2_mature', 'tree2_rife', 'tree2_infest', 'tree2_force_r', 'tree2_blackpod',
      'tree3_tiny', 'tree3_small', 'tree3_small2', 'tree3_large', 'tree3_mature', 'tree3_rife', 'tree3_infest', 'tree3_force_r', 'tree3_blackpod',
      'tree4_tiny', 'tree4_small', 'tree4_small2', 'tree4_large', 'tree4_mature', 'tree4_rife', 'tree4_infest', 'tree4_force_r', 'tree4_blackpod',
      'tree5_tiny', 'tree5_small', 'tree5_small2', 'tree5_large', 'tree5_mature', 'tree5_rife', 'tree5_infest', 'tree5_force_r', 'tree5_blackpod'
    ]

    CSV.generate(options) do |csv|
      csv << header_names
      Report.where(created_at: (date.beginning_of_day..date.end_of_day)).real.each do |report|
        csv << report.to_csv
      end
    end
  end

  def self.resumes(date = DateTime.yesterday)
    resumes = []
    date = date - 1.day

    Report.where(taken_at: (date.beginning_of_day..date.end_of_day)).real.group_by(&:region).each do |region, reports|
      resumes << Resume.new(date, region, reports)
    end

    resumes
  end

  #-----------------------#
  #   instance methods    #
  #-----------------------#

  def country
    if ['AS', 'BAR', 'CR', 'ER', 'WN', 'WS'].include?(region)
      return 'Ghana'
    else
      return 'Ivory Coast'
    end
  end

  def to_csv
    column_names = [
      'taken_at', 'site_reference', 'country', 'site_longitude', 'site_latitude', 'site_age', 'device', 'humidity', 'canopy', 'leaf', 'maintenance', 'flowers', 'bp', 'wilt', 'harvesting', 'drying', 'fertilizer'
    ]

    values = []

    column_names.each do |attributes|
      value = send(attributes)

      if value.is_a?(Device)
        values << value.to_s
      elsif value.is_a?(TrueClass) || value.is_a?(FalseClass)
        values << (value ? 1 : 0)
      else
        values << value
      end
    end

    trees.order(created_at: :asc).limit(5).each do |tree|
      values += tree.to_csv
    end

    values
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  protect_from_forgery except: :create
  load_and_authorize_resource except: [:create]

  def create
    @report = Report.new(report_params)

    if @report.save
      head :created
    else
      render plain: @report.errors.full_messages[0], status: 400
    end
  end

  def index
    if params[:date]
      @date = [Date.parse(params[:date]), (Date.today - 10.days)].max
    else
      @date = Date.today
    end

    @day_text = DayText.find_or_initialize_by(date: @date)
    @resumes = Report.resumes(@date)

    respond_to do |format|
      format.html
      format.csv { send_data "\uFEFF" +  Resume.to_csv(@resumes) }
    end
  end

  def raw
    if params[:date]
      @date = Date.parse(params[:date])
    else
      @date = Date.today
    end

    @day_text = DayText.find_or_initialize_by(date: @date)
    @reports = Report.where(created_at: (@date.beginning_of_day..@date.end_of_day)).real

    respond_to do |format|
      format.html
      format.csv { send_data "\uFEFF" + Report.to_csv(@date) }
    end
  end

  def demo
    if params[:date]
      @date = Date.parse(params[:date])
    else
      @date = Date.today
    end

    @reports = Report.where(created_at: (@date.beginning_of_day..@date.end_of_day)).demo

    respond_to do |format|
      format.html
    end
  end

  private

  def report_params
    if request.raw_post
      post_params = Rack::Utils.parse_nested_query(request.raw_post)
      params = ActionController::Parameters.new(Report.transpose_params(post_params))
    end

    params.require(:report).permit([
      :taken_at, :site_reference, :site_id, :visit_id, :humidity, :canopy,
      :leaf, :maintenance, :flowers, :bp, :harvesting, :drying, :fertilizer, :wilt, :region,
      :site_active_gps, :site_latitude, :site_longitude, :site_accuracy, :site_age, :device_id, :demo,
      {:trees_attributes => [:tiny, :small, :small2, :large, :mature, :rife, :infest, :force_r, :blackpod]}
    ])
  end
end

app/views/reports/demo.html.erb
<div class="date-select">
  <%= link_to '< ' + (@date - 1.day).strftime('%d.%m.%Y'), raw_reports_path(date: (@date - 1.day).to_param) %>
  <%= link_to (@date + 1.day).strftime('%d.%m.%Y') + ' >', raw_reports_path(date: (@date + 1.day).to_param) %>
</div>

<h1 class="title"><%= @date.strftime('%d.%m.%Y') %></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Report creation date</th>
        <th>Visit date</th>
        <th>Site reference</th>
        <th>Gps coordinates</th>
        <th>Age</th>
        <th>Ipad</th>
        <th>Humidity</th>
        <th>Canopy</th>
        <th>Leaf</th>
        <th>Maintenance</th>
        <th>Flowers</th>
        <th>Bp</th>
        <th>Wilt</th>
        <th>Harvesting</th>
        <th>Drying</th>
        <th>Fertilizer</th>
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.created_at.in_time_zone('CET').strftime('%d.%m.%Y %H:%M:%S %z') %></td>
          <td><%= report.taken_at.to_date.strftime('%d.%m.%Y') %></td>
          <td><%= report.site_reference %></td>
          <td><%= report.site_longitude %>/<%= report.site_latitude %></td>
          <td><%= report.site_age %></td>
          <td><%= report.device %></td>
          <td><%= report.humidity %></td>
          <td><%= report.canopy %></td>
          <td><%= report.leaf %></td>
          <td><%= report.maintenance %></td>
          <td><%= report.flowers %></td>
          <td><%= report.bp ? 'yes' : 'no' %></td>
          <td><%= report.wilt ? 'yes' : 'no' %></td>
          <td><%= report.harvesting ? 'yes' : 'no' %></td>
          <td><%= report.drying ? 'yes' : 'no' %></td>
          <td><%= report.fertilizer ? 'yes' : 'no' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/index.html.erb
<div class="date-select">
  <%= link_to '< ' + (@date - 1.day).strftime('%d.%m.%Y'), reports_path(date: (@date - 1.day).to_param), class: 'prev-date' if @date > (Date.today - 10.days)%>
  <%= link_to (@date + 1.day).strftime('%d.%m.%Y') + ' >', reports_path(date: (@date + 1.day).to_param), class: 'next-date' if @date < Date.today %>
</div>

<h1 class="title">Report - <%=  @date.strftime('%d.%m.%Y') %> </h1>

<% if @day_text.text.present? %>
  <div>
    <%= @day_text.text.html_safe %>
  </div>
<% end %>

<% if @resumes.empty? %>
  <h2>No data Available</h2>
<% else %>
  <%= link_to reports_path(date: @date.to_param, format: "csv"), class: 'btn btn-success add-button' do %>
    <i class="fa fa-download" aria-hidden="true"></i>
    Download CSV
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th class="first-col">Region(s)</th>
          <% @resumes.each do |resume| %>
            <th><%= resume.region %></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% Resume.headers.each do |attribute, name| %>
          <tr class="<%= attribute == :total_pods ? 'total' : '' %>">
            <th class="first-col"><%= name %></th>
            <% @resumes.each do |resume| %>
              <td>
                <% if resume.send(attribute).is_a?(Float) %>
                  <%= number_with_precision(resume.send(attribute), precision: 2)  %>
                <% else %>
                  <%= resume.send(attribute) %>
                <% end %>
              </td>
            <% end %>
          </tr>
          <% if [:nb_sites, :flowers, :total_pods].include?(attribute) %>
            <tr style="background-color: #fff;"><td colspan="<%= @resumes.count + 1 %>"></td></tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/reports/raw.html.erb
<div class="date-select">
  <%= link_to '< ' + (@date - 1.day).strftime('%d.%m.%Y'), raw_reports_path(date: (@date - 1.day).to_param), class: 'prev-date'  %>
  <%= link_to (@date + 1.day).strftime('%d.%m.%Y') + ' >', raw_reports_path(date: (@date + 1.day).to_param), class: 'next-date'  %>
</div>

<h1 class="title"><%= @date.strftime('%d.%m.%Y') %></h1>
<%= form_for(@day_text, url: day_texts_path, method: :post, remote: true) do |f| %>
  <%= f.hidden_field :date %>

  <div class="form-group">
    <%= f.text_area :text, :class => "tinymce", rows: 5 %>
    <%= tinymce %>
  </div>

  <%= f.submit 'save', class: 'btn btn-default' %>
<% end %>

<%= link_to raw_reports_path(format: "csv", date: @date.to_param), class: 'btn btn-success add-button' do %>
  <i class="fa fa-download" aria-hidden="true"></i>
  Dowload CSV
<% end %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Report creation date</th>
        <th>Visit date</th>
        <th>Site reference</th>
        <th>Gps coordinates</th>
        <th>Age</th>
        <th>Ipad</th>
        <th>Humidity</th>
        <th>Canopy</th>
        <th>Leaf</th>
        <th>Maintenance</th>
        <th>Flowers</th>
        <th>Bp</th>
        <th>Wilt</th>
        <th>Harvesting</th>
        <th>Drying</th>
        <th>Fertilizer</th>
      </tr>
    </thead>

    <tbody>
      <% @reports.each do |report| %>
        <tr>
          <td><%= report.created_at.in_time_zone('CET').strftime('%d.%m.%Y %H:%M:%S %z') %></td>
          <td><%= (report.taken_at + 1.day).to_date.strftime('%d.%m.%Y') %></td>
          <td><%= report.site_reference %></td>
          <td><%= report.site_longitude %>/<%= report.site_latitude %></td>
          <td><%= report.site_age %></td>
          <td><%= report.device %></td>
          <td><%= report.humidity %></td>
          <td><%= report.canopy %></td>
          <td><%= report.leaf %></td>
          <td><%= report.maintenance %></td>
          <td><%= report.flowers %></td>
          <td><%= report.bp ? 'yes' : 'no' %></td>
          <td><%= report.wilt ? 'yes' : 'no' %></td>
          <td><%= report.harvesting ? 'yes' : 'no' %></td>
          <td><%= report.drying ? 'yes' : 'no' %></td>
          <td><%= report.fertilizer ? 'yes' : 'no' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>