config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :day_texts, only: [:create]
  resources :reports, only: [:create, :index] do
    collection do
      get 'raw'
      get 'demo'
    end
  end

  root to: 'reports#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forestero" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/">Forestero</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'forestero-sa.com', 'http://www.forestero-sa.com', target: '_blank' %>
            </li>
            <% if current_user && current_user.admin? %>
              <li>
                <%= link_to 'Raw Data', raw_reports_path  %>
              </li>
              <li>
                <%= link_to 'Demo Data', demo_reports_path  %>
              </li>
            <% end %>
            <li>
              <% if current_user && current_user.admin? %>
                <%= link_to "Users", users_path  %>
              <% elsif current_user %>
                <%= link_to "Profile", edit_user_path(current_user.id)  %>
              <% end %>
            </li>
          </ul>
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to(destroy_user_session_path, :method => :delete ) do %>
                  <i class="fa fa-sign-out" aria-hidden="true"></i>Logout
                <% end %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Forestero</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>